# Generated by Django 4.0.4 on 2022-10-17 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 10, 17, 8, 49, 47, 899082))),
                ('note', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
