# Generated by Django 4.0.4 on 2022-10-18 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 13, 30, 13, 346165)),
        ),
    ]
